### ISSUE TITLE
Thank you for this and is it possible to always show panel on secondary monitor?

### ISSUE THREAD

**Issue by xjvs** [Noobsai/fullscreen-avoider#3]
I have no knowledge about gnome extension development, probably there is a good reason that show panel on secondary monitor only when the primary is in fullscreen mode, but I still want to ask whether it's possible to implement the feature of always showing the panel on secondary monitor?

And thanks again, great job.

**Comment by Noobsai** [comment]
You can change your primary display in the displays options:
![Screenshot from 2021-08-07 21-11-12](https://user-images.githubusercontent.com/17625194/128606567-56861531-8436-4be8-8e91-f9b6ec31a023.png)

**Comment by xjvs** [comment]
I want the  top panel show on both primary and secondary monitors, and not only when primary is in fullscreen mode.
But feel free to close this if this sounds not reasonable to you or there are some technical difficulties of implementing this.

**Comment by Noobsai** [comment]
Sorry, I initially misunderstood the question. 
Something similar to what you asked does [Multi Monitors Add-On](https://extensions.gnome.org/extension/921/multi-monitors-add-on/) (only for gnome shell ≤3.38). 
For your request an extension should creates a panelBox with all inner controls (see [mmpanel.js](https://github.com/spin83/multi-monitors-add-on/blob/0cec99d6ddedc0dc6b10d3c540390986b8fce4dc/multi-monitors-add-on%40spin83/mmpanel.js#L356)). But I don't know how other extensions will work with this custom panel. There is a lot of works and is not related to the idea of my extension.
My extension just moves the original panel to the secondary monitor by coordinates. I recreate hot corners only (because I cannot move them).

**Comment by xjvs** [comment]
I see, thanks for the info, closing this.

**Comment by realh** [comment]
Sorry for resurrecting a closed issue, but I'd just like to point out that if all @xjvs wants is to show the panel on the secondary monitor instead of the primary, as opposed to both, then that's definitely possible. I've just made a [new panel-mover extension](https://github.com/realh/panel-mover) based on this one, which lets you move the panel manually. I renamed it because the old name didn't describe the new behaviour well. I should probably add a hidden setting so that it remembers where you moved it to and restores that setting when you reload GNOME.
